[features]
seeds = false
skip-lint = false

[programs.localnet]
trust_vote = "3oWPRMbutojB8VSp5ApfVyNqiZg69Eti51aJ8uJ7Xw6q"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
client = "yarn run ts-node client/*.ts"

[toolchain]
anchor_version = "0.30.1"

[dependencies]
anchor-lang = "0.30.1"