const constituencies = [
    {
        province: 'kpk',
        constituencies: [
            { constituency: 'NA-1', area: 'Chitral' },
            { constituency: 'NA-2', area: 'Swat-I' },
            { constituency: 'NA-3', area: 'Swat-II' },
            { constituency: 'NA-4', area: 'Swat-III' },
            { constituency: 'NA-5', area: 'Upper Dir' },
            { constituency: 'NA-6', area: 'Lower Dir-I' },
            { constituency: 'NA-7', area: 'Lower Dir-II' },
            { constituency: 'NA-8', area: 'Malakand Protected Area' },
            { constituency: 'NA-9', area: 'Buner' },
            { constituency: 'NA-10', area: 'Shangla' },
            { constituency: 'NA-11', area: 'Kohistan' },
            { constituency: 'NA-12', area: 'Battagram' },
            { constituency: 'NA-13', area: 'Mansehra-I' },
            { constituency: 'NA-14', area: 'Mansehra-II' },
            { constituency: 'NA-15', area: 'Abbottabad-I' },
            { constituency: 'NA-16', area: 'Abbottabad-II' },
            { constituency: 'NA-17', area: 'Haripur' },
            { constituency: 'NA-18', area: 'Swabi-I' },
            { constituency: 'NA-19', area: 'Swabi-II' },
            { constituency: 'NA-20', area: 'Mardan-I' },
            { constituency: 'NA-21', area: 'Mardan-II' },
            { constituency: 'NA-22', area: 'Mardan-III' },
            { constituency: 'NA-23', area: 'Charsadda-I' },
            { constituency: 'NA-24', area: 'Charsadda-II' },
            { constituency: 'NA-25', area: 'Nowshera-I' },
            { constituency: 'NA-26', area: 'Nowshera-II' },
            { constituency: 'NA-27', area: 'Peshawar-I' },
            { constituency: 'NA-28', area: 'Peshawar-II' },
            { constituency: 'NA-29', area: 'Peshawar-III' },
            { constituency: 'NA-30', area: 'Peshawar-IV' },
            { constituency: 'NA-31', area: 'Peshawar-V' },
            { constituency: 'NA-32', area: 'Kohat' },
            { constituency: 'NA-33', area: 'Hangu' },
            { constituency: 'NA-34', area: 'Karak' },
            { constituency: 'NA-35', area: 'Bannu' },
            { constituency: 'NA-36', area: 'Lakki Marwat' },
            { constituency: 'NA-37', area: 'Tank' },
            { constituency: 'NA-38', area: 'Dera Ismail Khan-I' },
            { constituency: 'NA-39', area: 'Dera Ismail Khan-II' },
            { constituency: 'NA-40', area: 'Tribal Area-I (Bajaur Agency)' },
            { constituency: 'NA-41', area: 'Tribal Area-II (Bajaur Agency)' },
            { constituency: 'NA-42', area: 'Tribal Area-III (Mohmand Agency)' },
            { constituency: 'NA-43', area: 'Tribal Area-IV (Mohmand Agency)' },
            { constituency: 'NA-44', area: 'Tribal Area-V (Khyber Agency)' },
            { constituency: 'NA-45', area: 'Tribal Area-VI (Khyber Agency)' },
            { constituency: 'NA-46', area: 'Tribal Area-VII (Kurram Agency)' },
            { constituency: 'NA-47', area: 'Tribal Area-VIII (Kurram Agency)' },
            { constituency: 'NA-48', area: 'Tribal Area-IX (Orakzai Agency)' },
            { constituency: 'NA-49', area: 'Tribal Area-X (North Waziristan Agency)' },
            { constituency: 'NA-50', area: 'Tribal Area-XI (South Waziristan Agency)' },
            { constituency: 'NA-51', area: 'Tribal Area-XII (Frontier Regions)' },
            { constituency: 'NA-52', area: 'Tribal Area-XIII (Frontier Regions)' },
        ],
    },
];


const provincialConstituencies = [
    {
        "province": "kpk",
        "constituencies": [
            { "constituency": "PK-1", "area": "Upper Chitral" },
            { "constituency": "PK-2", "area": "Lower Chitral" },
            { "constituency": "PK-3", "area": "Swat-I" },
            { "constituency": "PK-4", "area": "Swat-II" },
            { "constituency": "PK-5", "area": "Swat-III" },
            { "constituency": "PK-6", "area": "Swat-IV" },
            { "constituency": "PK-7", "area": "Swat-V" },
            { "constituency": "PK-8", "area": "Swat-VI" },
            { "constituency": "PK-9", "area": "Swat-VII" },
            { "constituency": "PK-10", "area": "Swat-VIII" },
            { "constituency": "PK-11", "area": "Upper Dir-I" },
            { "constituency": "PK-12", "area": "Upper Dir-II" },
            { "constituency": "PK-13", "area": "Upper Dir-III" },
            { "constituency": "PK-14", "area": "Lower Dir-I" },
            { "constituency": "PK-15", "area": "Lower Dir-II" },
            { "constituency": "PK-16", "area": "Lower Dir-III" },
            { "constituency": "PK-17", "area": "Lower Dir-IV" },
            { "constituency": "PK-18", "area": "Lower Dir-V" },
            { "constituency": "PK-19", "area": "Bajaur-I" },
            { "constituency": "PK-20", "area": "Bajaur-II" },
            { "constituency": "PK-21", "area": "Bajaur-III" },
            { "constituency": "PK-22", "area": "Bajaur-IV" },
            { "constituency": "PK-23", "area": "Malakand-I" },
            { "constituency": "PK-24", "area": "Malakand-II" },
            { "constituency": "PK-25", "area": "Buner-I" },
            { "constituency": "PK-26", "area": "Buner-II" },
            { "constituency": "PK-27", "area": "Buner-III" },
            { "constituency": "PK-28", "area": "Shangla-I" },
            { "constituency": "PK-29", "area": "Shangla-II" },
            { "constituency": "PK-30", "area": "Shangla-III" },
            { "constituency": "PK-31", "area": "Upper Kohistan" },
            { "constituency": "PK-32", "area": "Lower Kohistan" },
            { "constituency": "PK-33", "area": "Kolai Palas Kohistan" },
            { "constituency": "PK-34", "area": "Battagram-I" },
            { "constituency": "PK-35", "area": "Battagram-II" },
            { "constituency": "PK-36", "area": "Mansehra-I" },
            { "constituency": "PK-37", "area": "Mansehra-II" },
            { "constituency": "PK-38", "area": "Mansehra-III" },
            { "constituency": "PK-39", "area": "Mansehra-IV" },
            { "constituency": "PK-40", "area": "Mansehra-V" },
            { "constituency": "PK-41", "area": "Tor Ghar" },
            { "constituency": "PK-42", "area": "Abbottabad-I" },
            { "constituency": "PK-43", "area": "Abbottabad-II" },
            { "constituency": "PK-44", "area": "Abbottabad-III" },
            { "constituency": "PK-45", "area": "Abbottabad-IV" },
            { "constituency": "PK-46", "area": "Haripur-I" },
            { "constituency": "PK-47", "area": "Haripur-II" },
            { "constituency": "PK-48", "area": "Haripur-III" },
            { "constituency": "PK-49", "area": "Swabi-I" },
            { "constituency": "PK-50", "area": "Swabi-II" },
            { "constituency": "PK-51", "area": "Swabi-III" },
            { "constituency": "PK-52", "area": "Swabi-IV" },
            { "constituency": "PK-53", "area": "Swabi-V" },
            { "constituency": "PK-54", "area": "Mardan-I" },
            { "constituency": "PK-55", "area": "Mardan-II" },
            { "constituency": "PK-56", "area": "Mardan-III" },
            { "constituency": "PK-57", "area": "Mardan-IV" },
            { "constituency": "PK-58", "area": "Mardan-V" },
            { "constituency": "PK-59", "area": "Mardan-VI" },
            { "constituency": "PK-60", "area": "Mardan-VII" },
            { "constituency": "PK-61", "area": "Charsadda-I" },
            { "constituency": "PK-62", "area": "Charsadda-II" },
            { "constituency": "PK-63", "area": "Charsadda-III" },
            { "constituency": "PK-64", "area": "Charsadda-IV" },
            { "constituency": "PK-65", "area": "Charsadda-V" },
            { "constituency": "PK-66", "area": "Mohmand-I" },
            { "constituency": "PK-67", "area": "Mohmand-II" },
            { "constituency": "PK-68", "area": "Khyber-I" },
            { "constituency": "PK-69", "area": "Khyber-II" },
            { "constituency": "PK-70", "area": "Khyber-III" },
            { "constituency": "PK-71", "area": "Peshawar-I" },
            { "constituency": "PK-72", "area": "Peshawar-II" },
            { "constituency": "PK-73", "area": "Peshawar-III" },
            { "constituency": "PK-74", "area": "Peshawar-IV" },
            { "constituency": "PK-75", "area": "Peshawar-V" },
            { "constituency": "PK-76", "area": "Peshawar-VI" },
            { "constituency": "PK-77", "area": "Peshawar-VII" },
            { "constituency": "PK-78", "area": "Peshawar-VIII" },
            { "constituency": "PK-79", "area": "Peshawar-IX" },
            { "constituency": "PK-80", "area": "Peshawar-X" },
            { "constituency": "PK-81", "area": "Peshawar-XI" },
            { "constituency": "PK-82", "area": "Peshawar-XII" },
            { "constituency": "PK-83", "area": "Peshawar-XIII" },
            { "constituency": "PK-84", "area": "Peshawar-XIV" },
            { "constituency": "PK-85", "area": "Nowshera-I" },
            { "constituency": "PK-86", "area": "Nowshera-II" },
            { "constituency": "PK-87", "area": "Nowshera-III" },
            { "constituency": "PK-88", "area": "Nowshera-IV" },
            { "constituency": "PK-89", "area": "Nowshera-V" },
            { "constituency": "PK-90", "area": "Kohat-I" },
            { "constituency": "PK-91", "area": "Kohat-II" },
            { "constituency": "PK-92", "area": "Kohat-III" },
            { "constituency": "PK-93", "area": "Hangu" },
            { "constituency": "PK-94", "area": "Orakzai" },
            { "constituency": "PK-95", "area": "Kurram-I" },
            { "constituency": "PK-96", "area": "Kurram-II" },
            { "constituency": "PK-97", "area": "Karak-I" },
            { "constituency": "PK-98", "area": "Karak-II" },
            { "constituency": "PK-99", "area": "Bannu-I" },
            { "constituency": "PK-100", "area": "Bannu-II" },
            { "constituency": "PK-101", "area": "Bannu-III" },
            { "constituency": "PK-102", "area": "Bannu-IV" },
            { "constituency": "PK-103", "area": "North Waziristan-I" },
            { "constituency": "PK-104", "area": "North Waziristan-II" },
            { "constituency": "PK-105", "area": "Lakki Marwat-I" },
            { "constituency": "PK-106", "area": "Lakki Marwat-II" },
            { "constituency": "PK-107", "area": "Lakki Marwat-III" },
            { "constituency": "PK-108", "area": "Tank" },
            { "constituency": "PK-109", "area": "South Waziristan Upper" },
            { "constituency": "PK-110", "area": "South Waziristan Lower" },
            { "constituency": "PK-111", "area": "Dera Ismail Khan-I" },
            { "constituency": "PK-112", "area": "Dera Ismail Khan-II" },
            { "constituency": "PK-113", "area": "Dera Ismail Khan-III" },
            { "constituency": "PK-114", "area": "Dera Ismail Khan-IV" },
            { "constituency": "PK-115", "area": "Dera Ismail Khan-V" }
        ]
    },
    {
        "province": "punjab",
        "constituencies": [
            { "constituency": "PP-1", "area": "Attock-I" },
            { "constituency": "PP-2", "area": "Attock-II" },
            { "constituency": "PP-3", "area": "Attock-III" },
            { "constituency": "PP-4", "area": "Attock-IV" },
            { "constituency": "PP-5", "area": "Attock-V" },
            { "constituency": "PP-6", "area": "Murree" },
            { "constituency": "PP-7", "area": "Rawalpindi-I" },
            { "constituency": "PP-8", "area": "Rawalpindi-II" },
            { "constituency": "PP-9", "area": "Rawalpindi-III" },
            { "constituency": "PP-10", "area": "Rawalpindi-IV" },
            { "constituency": "PP-11", "area": "Rawalpindi-V" },
            { "constituency": "PP-12", "area": "Rawalpindi-VI" },
            { "constituency": "PP-13", "area": "Rawalpindi-VII" },
            { "constituency": "PP-14", "area": "Rawalpindi-VIII" },
            { "constituency": "PP-15", "area": "Rawalpindi-IX" },
            { "constituency": "PP-16", "area": "Rawalpindi-X" },
            { "constituency": "PP-17", "area": "Rawalpindi-XI" },
            { "constituency": "PP-18", "area": "Rawalpindi-XII" },
            { "constituency": "PP-19", "area": "Rawalpindi-XIII" },
            { "constituency": "PP-20", "area": "Chakwal-I" },
            { "constituency": "PP-21", "area": "Chakwal-II" },
            { "constituency": "PP-22", "area": "Chakwal-cum-Talagang" },
            { "constituency": "PP-23", "area": "Talagang" },
            { "constituency": "PP-24", "area": "Jhelum-I" },
            { "constituency": "PP-25", "area": "Jhelum-II" },
            { "constituency": "PP-26", "area": "Jhelum-III" },
            { "constituency": "PP-27", "area": "Gujrat-I" },
            { "constituency": "PP-28", "area": "Gujrat-II" },
            { "constituency": "PP-29", "area": "Gujrat-III" },
            { "constituency": "PP-30", "area": "Gujrat-IV" },
            { "constituency": "PP-31", "area": "Gujrat-V" },
            { "constituency": "PP-32", "area": "Gujrat-VI" },
            { "constituency": "PP-33", "area": "Gujrat-VII" },
            { "constituency": "PP-34", "area": "Gujrat-VIII" },
            { "constituency": "PP-35", "area": "Wazirabad-I" },
            { "constituency": "PP-36", "area": "Wazirabad-II" },
            { "constituency": "PP-37", "area": "Hafizabad-I" },
            { "constituency": "PP-38", "area": "Hafizabad-II" },
            { "constituency": "PP-39", "area": "Hafizabad-III" },
            { "constituency": "PP-40", "area": "Mandi Bahauddin-I" },
            { "constituency": "PP-41", "area": "Mandi Bahauddin-II" },
            { "constituency": "PP-42", "area": "Mandi Bahauddin-III" },
            { "constituency": "PP-43", "area": "Mandi Bahauddin-IV" },
            { "constituency": "PP-44", "area": "Sialkot-I" },
            { "constituency": "PP-45", "area": "Sialkot-II" },
            { "constituency": "PP-46", "area": "Sialkot-III" },
            { "constituency": "PP-47", "area": "Sialkot-IV" },
            { "constituency": "PP-48", "area": "Sialkot-V" },
            { "constituency": "PP-49", "area": "Sialkot-VI" },
            { "constituency": "PP-50", "area": "Sialkot-VII" },
            { "constituency": "PP-51", "area": "Sialkot-VIII" },
            { "constituency": "PP-52", "area": "Sialkot-IX" },
            { "constituency": "PP-53", "area": "Sialkot-X" },
            { "constituency": "PP-54", "area": "Narowal-I" },
            { "constituency": "PP-55", "area": "Narowal-II" },
            { "constituency": "PP-56", "area": "Narowal-III" },
            { "constituency": "PP-57", "area": "Narowal-IV" },
            { "constituency": "PP-58", "area": "Narowal-V" },
            { "constituency": "PP-59", "area": "Gujranwala-I" },
            { "constituency": "PP-60", "area": "Gujranwala-II" },
            { "constituency": "PP-61", "area": "Gujranwala-III" },
            { "constituency": "PP-62", "area": "Gujranwala-IV" },
            { "constituency": "PP-63", "area": "Gujranwala-V" },
            { "constituency": "PP-64", "area": "Gujranwala-VI" },
            { "constituency": "PP-65", "area": "Gujranwala-VII" },
            { "constituency": "PP-66", "area": "Gujranwala-VIII" },
            { "constituency": "PP-67", "area": "Gujranwala-IX" },
            { "constituency": "PP-68", "area": "Gujranwala-X" },
            { "constituency": "PP-69", "area": "Gujranwala-XI" },
            { "constituency": "PP-70", "area": "Gujranwala-XII" },
            { "constituency": "PP-71", "area": "Sargodha-I" },
            { "constituency": "PP-72", "area": "Sargodha-II" },
            { "constituency": "PP-73", "area": "Sargodha-III" },
            { "constituency": "PP-74", "area": "Sargodha-IV" },
            { "constituency": "PP-75", "area": "Sargodha-V" },
            { "constituency": "PP-76", "area": "Sargodha-VI" },
            { "constituency": "PP-77", "area": "Sargodha-VII" },
            { "constituency": "PP-78", "area": "Sargodha-VIII" },
            { "constituency": "PP-79", "area": "Sargodha-IX" },
            { "constituency": "PP-80", "area": "Sargodha-X" },
            { "constituency": "PP-81", "area": "Khushab-I" },
            { "constituency": "PP-82", "area": "Khushab-II" },
            { "constituency": "PP-83", "area": "Khushab-III" },
            { "constituency": "PP-84", "area": "Khushab-IV" },
            { "constituency": "PP-85", "area": "Mianwali-I" },
            { "constituency": "PP-86", "area": "Mianwali-II" },
            { "constituency": "PP-87", "area": "Mianwali-III" },
            { "constituency": "PP-88", "area": "Mianwali-IV" },
            { "constituency": "PP-89", "area": "Bhakkar-I" },
            { "constituency": "PP-90", "area": "Bhakkar-II" },
            { "constituency": "PP-91", "area": "Bhakkar-III" },
            { "constituency": "PP-92", "area": "Bhakkar-IV" },
            { "constituency": "PP-93", "area": "Bhakkar-V" },
            { "constituency": "PP-94", "area": "Chiniot-I" },
            { "constituency": "PP-95", "area": "Chiniot-II" },
            { "constituency": "PP-96", "area": "Chiniot-III" },
            { "constituency": "PP-97", "area": "Chiniot-IV" },
            { "constituency": "PP-98", "area": "Faisalabad-I" },
            { "constituency": "PP-99", "area": "Faisalabad-II" },
            { "constituency": "PP-100", "area": "Faisalabad-III" },
            { "constituency": "PP-101", "area": "Faisalabad-IV" },
            { "constituency": "PP-102", "area": "Faisalabad-V" },
            { "constituency": "PP-103", "area": "Faisalabad-VI" },
            { "constituency": "PP-104", "area": "Faisalabad-VII" },
            { "constituency": "PP-105", "area": "Faisalabad-VIII" },
            { "constituency": "PP-106", "area": "Faisalabad-IX" },
            { "constituency": "PP-107", "area": "Faisalabad-X" },
            { "constituency": "PP-108", "area": "Faisalabad-XI" },
            { "constituency": "PP-109", "area": "Faisalabad-XII" },
            { "constituency": "PP-110", "area": "Faisalabad-XIII" },
            { "constituency": "PP-111", "area": "Faisalabad-XIV" },
            { "constituency": "PP-112", "area": "Toba Tek Singh-I" },
            { "constituency": "PP-113", "area": "Toba Tek Singh-II" },
            { "constituency": "PP-114", "area": "Toba Tek Singh-III" },
            { "constituency": "PP-115", "area": "Toba Tek Singh-IV" },
            { "constituency": "PP-116", "area": "Jhang-I" },
            { "constituency": "PP-117", "area": "Jhang-II" },
            { "constituency": "PP-118", "area": "Jhang-III" },
            { "constituency": "PP-119", "area": "Jhang-IV" },
            { "constituency": "PP-120", "area": "Jhang-V" },
            { "constituency": "PP-121", "area": "Chiniot-I" },
            { "constituency": "PP-122", "area": "Chiniot-II" },
            { "constituency": "PP-123", "area": "Chiniot-III" },
            { "constituency": "PP-124", "area": "Chiniot-IV" },
            { "constituency": "PP-125", "area": "Sargodha-I" },
            { "constituency": "PP-126", "area": "Sargodha-II" },
            { "constituency": "PP-127", "area": "Sargodha-III" },
            { "constituency": "PP-128", "area": "Sargodha-IV" },
            { "constituency": "PP-129", "area": "Sargodha-V" },
            { "constituency": "PP-130", "area": "Sargodha-VI" },
            { "constituency": "PP-131", "area": "Sargodha-VII" },
            { "constituency": "PP-132", "area": "Sargodha-VIII" },
            { "constituency": "PP-133", "area": "Khushab-I" },
            { "constituency": "PP-134", "area": "Khushab-II" },
            { "constituency": "PP-135", "area": "Khushab-III" },
            { "constituency": "PP-136", "area": "Khushab-IV" },
            { "constituency": "PP-137", "area": "Mianwali-I" },
            { "constituency": "PP-138", "area": "Mianwali-II" },
            { "constituency": "PP-139", "area": "Mianwali-III" },
            { "constituency": "PP-140", "area": "Mianwali-IV" },
            { "constituency": "PP-141", "area": "Bhakkar-I" },
            { "constituency": "PP-142", "area": "Bhakkar-II" },
            { "constituency": "PP-143", "area": "Bhakkar-III" },
            { "constituency": "PP-144", "area": "Bhakkar-IV" },
            { "constituency": "PP-145", "area": "Bahawalpur-I" },
            { "constituency": "PP-146", "area": "Bahawalpur-II" },
            { "constituency": "PP-147", "area": "Bahawalpur-III" },
            { "constituency": "PP-148", "area": "Bahawalpur-IV" },
            { "constituency": "PP-149", "area": "Bahawalpur-V" },
            { "constituency": "PP-150", "area": "Bahawalnagar-I" },
            { "constituency": "PP-151", "area": "Bahawalnagar-II" },
            { "constituency": "PP-152", "area": "Bahawalnagar-III" },
            { "constituency": "PP-153", "area": "Bahawalnagar-IV" },
            { "constituency": "PP-154", "area": "Bahawalnagar-V" },
            { "constituency": "PP-155", "area": "Rahim Yar Khan-I" },
            { "constituency": "PP-156", "area": "Rahim Yar Khan-II" },
            { "constituency": "PP-157", "area": "Rahim Yar Khan-III" },
            { "constituency": "PP-158", "area": "Rahim Yar Khan-IV" },
            { "constituency": "PP-159", "area": "Rahim Yar Khan-V" },
            { "constituency": "PP-160", "area": "Rahim Yar Khan-VI" },
            { "constituency": "PP-161", "area": "Rahim Yar Khan-VII" },
            { "constituency": "PP-162", "area": "Dera Ghazi Khan-I" },
            { "constituency": "PP-163", "area": "Dera Ghazi Khan-II" },
            { "constituency": "PP-164", "area": "Dera Ghazi Khan-III" },
            { "constituency": "PP-165", "area": "Dera Ghazi Khan-IV" },
            { "constituency": "PP-166", "area": "Rajanpur-I" },
            { "constituency": "PP-167", "area": "Rajanpur-II" },
            { "constituency": "PP-168", "area": "Rajanpur-III" },
            { "constituency": "PP-169", "area": "Muzaffargarh-I" },
            { "constituency": "PP-170", "area": "Muzaffargarh-II" },
            { "constituency": "PP-171", "area": "Muzaffargarh-III" },
            { "constituency": "PP-172", "area": "Muzaffargarh-IV" },
            { "constituency": "PP-173", "area": "Muzaffargarh-V" },
            { "constituency": "PP-174", "area": "Layyah-I" },
            { "constituency": "PP-175", "area": "Layyah-II" },
            { "constituency": "PP-176", "area": "Layyah-III" },
            { "constituency": "PP-177", "area": "Layyah-IV" },
            { "constituency": "PP-178", "area": "Vehari-I" },
            { "constituency": "PP-179", "area": "Vehari-II" },
            { "constituency": "PP-180", "area": "Vehari-III" },
            { "constituency": "PP-181", "area": "Vehari-IV" },
            { "constituency": "PP-182", "area": "Multan-I" },
            { "constituency": "PP-183", "area": "Multan-II" },
            { "constituency": "PP-184", "area": "Multan-III" },
            { "constituency": "PP-185", "area": "Multan-IV" },
            { "constituency": "PP-186", "area": "Multan-V" },
            { "constituency": "PP-187", "area": "Multan-VI" },
            { "constituency": "PP-188", "area": "Khanewal-I" },
            { "constituency": "PP-189", "area": "Khanewal-II" },
            { "constituency": "PP-190", "area": "Khanewal-III" },
            { "constituency": "PP-191", "area": "Khanewal-IV" },
            { "constituency": "PP-192", "area": "Lodhran-I" },
            { "constituency": "PP-193", "area": "Lodhran-II" },
            { "constituency": "PP-194", "area": "Lodhran-III" },
            { "constituency": "PP-195", "area": "Rahim Yar Khan-I" },
            { "constituency": "PP-196", "area": "Rahim Yar Khan-II" },
            { "constituency": "PP-197", "area": "Rahim Yar Khan-III" },
            { "constituency": "PP-198", "area": "Rahim Yar Khan-IV" },
            { "constituency": "PP-199", "area": "Bahawalpur-I" },
            { "constituency": "PP-200", "area": "Bahawalpur-II" }
        ]
    }

]